### ISSUE TITLE
vs-rgtools breaks vs-dehalo

### ISSUE THREAD

**Issue by nobananasforyou** [Setsugennoao/vs-rgtools#6]
Hello,

I tried using vs-dehalo's fine_dehalo but it currently doesn't work, same with YAHR.

Script:
import vapoursynth as vs
from vsdehalo import fine_dehalo
core = vs.core

src = core.d2v.Source(r'sti_01.d2v', rff=False)
src = fine_dehalo(src)
src.set_output()

vsedit:
Failed to evaluate the script:
Python exception: cannot import name 'iterate' from 'vsrgtools.util' (C:\Program Files\Python310\lib\site-packages\vsrgtools\util.py)

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate
File "D:/Encoding/Projects/sti_01 - Copy (2).vpy", line 2, in 
from vsdehalo import fine_dehalo
File "C:\Program Files\Python310\lib\site-packages\vsdehalo\__init__.py", line 3, in 
from . import alpha, masks, utils, warp
File "C:\Program Files\Python310\lib\site-packages\vsdehalo\alpha.py", line 15, in 
from . import masks
File "C:\Program Files\Python310\lib\site-packages\vsdehalo\masks.py", line 5, in 
from vsrgtools.util import PlanesT, iterate, norm_expr_planes, wmean_matrix
ImportError: cannot import name 'iterate' from 'vsrgtools.util' (C:\Program Files\Python310\lib\site-packages\vsrgtools\util.py)

P.S. How do I use vsdehalo's YAHRmask from YAHRmod or YAHR vanilla? What is PlanesT and what does it do?

Kind Regards

**Comment by Setsugennoao** [comment]
Sorry, bumped up version now
